### ISSUE TITLE
Cannot delete Machine with `.spec.providerID=nil`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/machine-controller-manager-provider-alicloud#92]
**What happened**:
Cannot delete a Machine without `providerID`.

It fails with:

```yaml
  lastOperation:
    description: |-
      VM deletion failed due to - machine codes error: code = [Internal] message = [SDK.ServerError
      ErrorCode: MissingParameter
      Recommend: https://api.aliyun.com/troubleshoot?q=MissingParameter&product=Ecs&requestId=foo
      RequestId: foo
      Message: The input parameter "InstanceId" that is mandatory for processing this request is not supplied.]. Aborting operation. Initiate VM deletion
    lastUpdateTime: "2025-03-14T15:08:57Z"
    state: Failed
    type: Delete
```

We have several Machines hanged in `Terminating` state with this error.

The Machine spec:
```yaml
spec:
  class:
    kind: MachineClass
    name: shoot--proj--baz-worker-e0nwr-zone-a5605
  nodeTemplate:
    metadata:
      creationTimestamp: null
      labels:
        kubernetes.io/arch: amd64
        networking.gardener.cloud/node-local-dns-enabled: "true"
        node.kubernetes.io/role: node
        topology.diskplugin.csi.alibabacloud.com/zone: zone
        worker.garden.sapcloud.io/group: worker-e0nwr
        worker.gardener.cloud/cri-name: containerd
        worker.gardener.cloud/gardener-node-agent-secret-name: gardener-node-agent-worker-e0nwr-47ea5268193b803c
        worker.gardener.cloud/pool: worker-e0nwr
        worker.gardener.cloud/system-components: "true"
    spec: {}
```

As you can see, it does not have `.spec.providerID` set.

---

See the creation and deletion timestamps of one affected Machine:
```
apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  creationTimestamp: "2025-03-11T16:01:40Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2025-03-11T16:01:41Z"
```

**What you expected to happen**:
Machine without providerID to be successfully deleted.

A similar logic exists in machine-controller-manager-provider-aws: https://github.com/gardener/machine-controller-manager-provider-aws/blob/6c49674f3117a4ed09aab899fab30fdb6393a315/pkg/aws/core.go#L358-L392

When the providerID is not set, it tries to find the corresponding VM using tags.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alicloud Shoot
2. Increase the minimum of a worker pool to trigger new Machine creation
3. When Machine is being created delete the Machine and later on restart the MCM Pod
4. As the Machine creation did not complete yet, you should see that its providerID is not set and the deletion fails with the above error.

**Anything else we need to know**:

**Environment**:
Version: v0.12.0
